version: 2

builds:
  - goos:
    - linux
    - darwin
    - windows
    - freebsd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
