version: 2

# Define builds first
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    tags:
      - ""
    binary: monokit

  - id: withapi
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    tags:
      - with_api
    binary: monokit
    # Add hooks to build frontend only
    hooks:
      pre: 
        - sh -c "make clean-frontend && make build-frontend"

  # Plugin builds
  - id: k8sHealth-plugin
    main: ./k8sHealth/cmd/plugin/main.go
    binary: k8sHealth
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    env:
      - CGO_ENABLED=0
    tags:
      - plugin
    dir: k8sHealth

archives:
  - id: default
    ids:
      - default
      - k8sHealth-plugin
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # Include plugins and config files in archives
    files:
      - README.md
      - LICENSE
      - config/*.yml
    
  - id: withapi
    ids:
      - withapi
      - k8sHealth-plugin
    name_template: "{{ .ProjectName }}_withapi_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # Include plugins and config files in archives
    files:
      - README.md
      - LICENSE
      - config/*.yml
