version: 2

# Define builds first
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    tags:
      - ""
    binary: monokit

  - id: withapi
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    tags:
      - with_api
    binary: monokit

  # Plugin builds
  - id: k8sHealth-plugin
    main: ./cmd/plugin/main.go
    binary: k8sHealth
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    tags:
      - plugin
    dir: k8sHealth

  - id: redisHealth-plugin
    main: ./cmd/plugin/main.go
    binary: redisHealth
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    tags:
      - plugin
    dir: redisHealth

  - id: wppconnectHealth-plugin

    main: ./cmd/plugin/main.go
    binary: wppconnectHealth
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    tags:
      - plugin
    dir: wppconnectHealth

  - id: pritunlHealth-plugin
    main: ./cmd/plugin/main.go
    binary: pritunlHealth
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    tags:
      - plugin
    dir: pritunlHealth

  - id: zimbraHealth-plugin
    main: ./cmd/plugin/main.go
    binary: zimbraHealth
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    env:
      - CGO_ENABLED=0
    tags:
      - plugin
    dir: zimbraHealth

archives:
  # Main monokit binary for all platforms
  - id: default
    ids:
      - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config/*.yml
      - config/*.yaml
    
  # Monokit with API support (Linux only)
  - id: withapi
    ids:
      - withapi
    name_template: "{{ .ProjectName }}_withapi_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config/*.yml
      - config/*.yaml

  # k8sHealth plugin (all platforms)
  - id: k8sHealth
    ids:
      - k8sHealth-plugin
    name_template: "{{ .ProjectName }}_k8sHealth_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  # redisHealth plugin (Linux only)
  - id: redisHealth
    ids:
      - redisHealth-plugin
    name_template: "{{ .ProjectName }}_redisHealth_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  # wppconnectHealth plugin (Linux only)
  - id: wppconnectHealth
    ids:
      - wppconnectHealth-plugin
    name_template: "{{ .ProjectName }}_wppconnectHealth_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  # pritunlHealth plugin (Linux only)
  - id: pritunlHealth
    ids:
      - pritunlHealth-plugin
    name_template: "{{ .ProjectName }}_pritunlHealth_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

  # zimbraHealth plugin (Linux only)
  - id: zimbraHealth
    ids:
      - zimbraHealth-plugin
    name_template: "{{ .ProjectName }}_zimbraHealth_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
