version: 2

# Define builds first
builds:
  - id: default
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    tags:
      - ""
    binary: monokit

  - id: withapi
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/monobilisim/monokit/common.MonokitVersion={{ .Version }}
    tags:
      - with_api
    binary: monokit
    # Add a hook specific to the withapi build
    hooks:
      pre: 
        - sh -c "make clean-frontend && make build-frontend"

archives:
  - id: default
    builds:
      - default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    
  - id: withapi
    builds:
      - withapi
    name_template: "{{ .ProjectName }}_withapi_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
