apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8shealth-cronjob
spec:
  schedule: "*/2 * * * *"  # Run every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8shealth-sa
          initContainers:
          - name: init-kubeconfig
            image: busybox
            command: ['sh', '-c', 'mkdir -p /root/.kube && touch /root/.kube/config && chmod 600 /root/.kube/config && rm -f /etc/mono/client.yml']
            volumeMounts:
            - name: kubeconfig-dir
              mountPath: /root/.kube
            - name: etc-mono-dir
              mountPath: /etc/mono
          containers:
          - name: k8shealth
            image: ghcr.io/monobilisim/monokit
            command:
            - "monokit"
            - "k8sHealth"
            env:
            - name: MONOKIT_NOCOLOR
              value: "true"
            volumeMounts:
            - name: config-volume
              mountPath: /etc/mono/k8s.yml
              subPath: k8s.yml
            - name: global-config-volume
              mountPath: /etc/mono/global.yml
              subPath: global.yml
            - name: kubeconfig-dir
              mountPath: /root/.kube
            - name: etc-mono-dir
              mountPath: /etc/mono
            - name: tmp-mono
              mountPath: /tmp/mono
          volumes:
          - name: config-volume
            configMap:
              name: k8shealth-config
          - name: global-config-volume
            configMap:
              name: monokit-global-config
          - name: kubeconfig-dir
            emptyDir: {}
          - name: etc-mono-dir
            emptyDir: {}
          - name: tmp-mono
            persistentVolumeClaim:
              claimName: k8shealth-tmp-mono-pvc
          restartPolicy: OnFailure
