apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml
- rbac.yaml
- pvc.yaml
- configmap.yaml
- global-configmap.yaml
- cronjob.yaml

images:
- name: ghcr.io/monobilisim/monokit
  newTag: latest
