apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8shealth-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8shealth-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces"]
  verbs: ["get", "list"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8shealth-rb
subjects:
- kind: ServiceAccount
  name: k8shealth-sa
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: k8shealth-role
  apiGroup: rbac.authorization.k8s.io