pmg:
  queue_limit: 50
  blacklist_check:
    enabled: false
    ip: ""  # Leave empty to auto-detect external IP
    ignorelist:  # List of blacklist names to ignore
      - "TIMEOUT"
      - "Example Blacklist"

postal:
  message_threshold: 100
  held_treshold: 100
  check_message: true

zimbra:
  z_url: example.com
  restart: false
  queue_limit: 50
  restart_limit: 2
  cache_interval: 12   # hours between full health checks (default: 12)
  webhook_tail:
    logfile: /opt/zimbra/log/cbpolicyd.log
    filter: 'test'
    stream: 'teststream'
    topic: 'testserver-logs'
  login_test:
    enabled: false
    username: 'test@example.com'
    password: 'testpassword'
  email_send_test:
    enabled: false
    from_email: ''  # Optional: defaults to login_test username if empty
    to_email: 'test@example.com'
    smtp_server: 'localhost'
    smtp_port: 587
    use_tls: true
    subject: 'Zimbra Health Check Test Email'  # Will be made unique with timestamp
    # Email checking configuration (to verify email was received)
    check_received: false  # Enable to check if email was actually received
    imap_server: 'localhost'
    imap_port: 993
    imap_use_tls: true
    to_email_username: ''                  # Username for IMAP login (defaults to to_email if empty)
    to_email_password: 'testpassword'      # Password for IMAP login
    check_retries: 3                       # Number of retry attempts (default: 3)
    check_retry_interval: 30               # Seconds between retry attempts (default: 30)
