pmg:
  queue_limit: 50
  blacklist_check:
    enabled: false
    ip: ""  # Leave empty to auto-detect external IP
    ignorelist:  # List of blacklist names to ignore
      - "TIMEOUT"
      - "Example Blacklist"

postal:
  message_threshold: 100
  held_treshold: 100
  check_message: true

zimbra:
  z_url: example.com
  restart: false
  queue_limit: 50
  restart_limit: 2
  webhook_tail:
    logfile: /opt/zimbra/log/cbpolicyd.log
    filter: 'test'
    stream: 'teststream'
    topic: 'testserver-logs'
  login_test:
    enabled: false
    username: 'test@example.com'
    password: 'testpassword'
  email_send_test:
    enabled: false
    from_email: ''  # Optional: defaults to login_test username if empty
    to_email: 'test@example.com'
    smtp_server: 'localhost'
    smtp_port: 587
    use_tls: true
    subject: 'Zimbra Health Check Test Email'
