filesystems:
- ext4
- ext3
- ext2
- xfs
- btrfs
- zfs
- fat32
- vfat

system_load_and_ram: true
part_use_limit: 90
dynamic_limit_interval: 0
top_processes:
  load_enabled: true
  load_processes: 20
  ram_enabled: true
  ram_processes: 20

load:
  limit_multiplier: 0.8
  issue_interval: 1
  issue_multiplier: 1
  limit: 20

ram_limit: 91

# ZFS configuration
# auto_clear: only if set to true, ZFS pools will be automatically cleared when degraded
#            if omitted or set to false, degraded pools will be reported but not cleared
zfs: # auto_clear: true  # Enable to allow automatic clearing

alarm:
  enabled: true
