port: 9989
postgres:
  host: localhost
  port: 5432
  user: monokit
  password: monokit
  dbname: monokit
keycloak:
  enabled: true 
  url: "https://keycloak.example.com/auth"
  realm: "monokit"
  clientId: "monokit-api"
  clientSecret: "your-client-secret"
  disableLocalAuth: false
